Milestone 5 [Bookstore]: Styling
Microverse-Fullstack-Program/bookstore pull request #17
Opened 2023-02-13 00:20 UTC by cherelemma

# Implementation Summary

In this milestone bookstore project, the website is styled following react best practices and language style guides in code.

## General Requirements

✅  No linters error.
✅  Followed the Git-flow.
✅ Followed JS, HTML&CSS best practices
✅  Documented work professionally.

2023-02-13 07:43 UTC, TedLivist requested changes
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @cherelemma,

Good job so far!
✔️ Good documentation
✔️ Nice styling of navbar
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
_Check the comments under the review._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-13 07:43 UTC, TedLivist commented on src/components/Book.js
> +      </div>
- [ ] Kindly note that you are required to replicate the styling exactly as it is on the design. Kindly use the correct fonts and sizes for the texts as we have in the design.

- [ ] Kindly take note of the background color. The original design has a somewhat lighter grey color but yours is darker. Kindly fix that as well.

  Your Implementation | Zeplin Design
  :---:|:---:
  ![wiwow](https://user-images.githubusercontent.com/36542986/218398281-0ef7cd1f-4389-4bd9-930f-0f3824722f5c.jpg) | ![euwo](https://user-images.githubusercontent.com/36542986/218398286-7c8820f1-adf6-4d3a-a028-d64432e99868.jpg)

2023-02-13 07:43 UTC, TedLivist commented on src/components/NewBook.js
>            value={userInput.title}
- [ ] Kindly ensure you style the form component as well to fit the design - noting the fonts and sizes of the text.

  Your Implementation | Zeplin Design
  :---:|:---:
  ![wqp](https://user-images.githubusercontent.com/36542986/218398559-6af6cba8-1ccd-4d3f-982b-9be11e4a9f69.jpg) | ![ewpw](https://user-images.githubusercontent.com/36542986/218398554-eca0d06e-c6b7-43e0-80eb-715cadca171f.jpg)

2023-02-14 09:04 UTC, mckent05 approved these changes
Hi @cherelemma, 

# STATUS: APPROVED ✔️ ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations and well done! 🎉 
![approved](https://user-images.githubusercontent.com/73607512/207264357-1b05ce6a-95f2-4d31-9c26-888c6ddfa124.gif)


## Highlights
- All linter checks are passing ✔️ ✔️ 
- Your PR is professional 👏 👏 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-14 09:12 UTC, merged